language: node_js
node_js: stable     #设置相应的版本
cache:
    directories:
        - node_modules
#before_install:
  #- npm install -g hexo
  #- npm install -g hexo-cli

# S: Build Lifecycle
install:
  - npm install

before_script:
   - export TZ='Asia/Shanghai'  
 # - npm install -g gulp
 # - git clone --branch master https://github.com/imcco/imcco.github.io.git public

script:
  #- hexo cl #清除
  - hexo g   #生成

after_script:
  - cd ./public
  - git init
  - git config user.name "imcco"
  - git config user.email "ceek@vip.qq.com"
  - git add .
  - git commit -m "Update Blog By TravisCI,Deploy at $(date)."
  # Github Pages
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master 
  # Coding Pages
  - git push --force --quiet "https://laukei:${CO_TOKEN}@${CO_REF}" master:master
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --quiet "https://${GH_TOKEN}@${GH_REF}" master:master --tags
  # Coding Pages
  - git push --quiet "https://laukei:${CO_TOKEN}@${CO_REF}" master:master --tags

branches:
  only:
    - dev

env:
 global:
   # Github Pages
   - GH_REF: github.com/imcco/imcco.github.io.git
   # Coding Pages
   - CO_REF: git@e.coding.net:laukei/laukei.coding.me.git
